### ISSUE TITLE
raise IOError("extracting SIFT features failed " + resultname)

### ISSUE THREAD

**Issue by Mario92V** [shackenberg/Minimal-Bag-of-Visual-Words-Image-Classifier#10]
Hello, how are you? I'm using your code and works nicely (thanks for that job by the way) but I'm trying to classify an image that I'm getting from a database in a host, and I'm getting this error (you can see it better in the attached file). With other images taken from a cellphone for example this error doesn't occur but with this image from the database happens. Thank you for your time.

![file](https://cloud.githubusercontent.com/assets/17289765/13104388/d59c8828-d52a-11e5-8ba4-f344ba030da1.png)

**Comment by shackenberg** [comment]
Hi Mario,

thanks for the nice words. This issue looks strange.  Can you post the full command for a working example? 

Also it says that there is a permission issue with `./sift`

**Comment by Mario92V** [comment]
Hello. Thank you for your answer, you are right, the problem was a permission issue. The first image is the ls -la result. After that with chmod +x sift obtained the second image and with that I can finally classify images coming from the host. I will close this issue, thank you again for your time.
![pre_chmod](https://cloud.githubusercontent.com/assets/17289765/13160897/743693c8-d668-11e5-9d77-7603d0d538a7.png)
![pos_chmod](https://cloud.githubusercontent.com/assets/17289765/13160901/783c0778-d668-11e5-8e56-2a7d86e29160.png)
