### ISSUE TITLE
Obtain more than one result for classification

### ISSUE THREAD

**Issue by Mario92V** [shackenberg/Minimal-Bag-of-Visual-Words-Image-Classifier#12]
Hello it's me again. Is there any way to get the three most likely classes with classify.py and the confidence measurement to each one of them. I don't know if the question is clear enough. Thank you for your time again.

**Comment by shackenberg** [comment]
Hi Mario, sorry, I don't think it is doable very easily as classify depends on the output of the svm binary. You could always try https://github.com/shackenberg/phow_caltech101.py which gives much better control over these things.

**Comment by Mario92V** [comment]
Hi, sorry I thought I answered this before, thanks for your help.
