### ISSUE TITLE
Increasing accuracy

### ISSUE THREAD

**Issue by IshaanGupta5** [shackenberg/Minimal-Bag-of-Visual-Words-Image-Classifier#15]
Hi.Hope you're doing fine.I need some help.

I've been running your code for classifying food images(banana,strawberry,pizza,donuts etc).So far the accuracy comes out to be 72% and I was hoping if there were any ways to increase it.

I read up on the net and found that normalizing the features in k-means clustering gives better results.Also,I read up on how SIFT features are computed and found that the images are scaled before hand.Do they provide the same functionality?

Do you know any way to increase the accuracy?Also, how did you decide that the number of clusters will be the square root of the number of features?

Any insight is appreciated.Thanks.

**Comment by shackenberg** [comment]
Dear Ishaan Gupta,

please have a look at https://github.com/shackenberg/phow_caltech101.py. As written in the [`readme`](https://github.com/shackenberg/Minimal-Bag-of-Visual-Words-Image-Classifier/blob/master/README.md) the phow_caltech code is very simliar but should provide much better results. And if you really need much better or state of the art performance you need to look into [deep learning](http://benanne.github.io/2015/03/17/plankton.html).

Ludwig

**Comment by IshaanGupta5** [comment]
I found the link https://github.com/shackenberg/phow_caltech101.py but thought that it would only provide faster computation, not accuracy.I'll surely give this a try then.
Thank you again for the deep learning link and for the help.Really appreciate it.

**Comment by shackenberg** [comment]
> but thought that it would only provide faster computation, not accuracy.
Dear Ishaan Gupta, that is a good point. I will need to make that clearer in the readme.
